### ISSUE TITLE
Faulty plugin on new project

### ISSUE THREAD

**Issue by ShinobiWPS** [callstack/parcel-plugin-linaria#13] opened 2019-09-18 16:14 UTC
## Environment
files are .js (not .jsx)

## Description

New project with Parcel
installed linaria,
installed plugin,
error.

## Reproducible Demo

https://send.firefox.com/download/602e35e719ad22f9/#eue9cTl9rNs1MolN9Y_x3g

**Comment by jayu** [comment] 2020-03-26 13:08
I cannot reproduce the issue. The link has expired :/ If it still an issue, please update the repro and maybe share more info about the error you got. I'm closing it for now

**Closed as completed by jayu** 2020-03-26 13:08 UTC
